// The site's public identity in one place: the canonical origin, the name, and
// the share image. Dependency-free apart from the image path, so the pure lib
// modules and their tests can use it as well as the Next.js metadata files.

import { IMAGES } from "../content/assets.ts";

/**
 * Canonical origin. Punycode, because that is the form search engines and the
 * Host header carry (see the IDN note in the workspace AGENTS.md).
 */
export const SITE_URL = "https://xn--tekse-cua.ee";

export const SITE_NAME = "Õtekse";

/** The name as it is typed on a keyboard without õ. */
export const SITE_ALTERNATE_NAME = "Otekse";

/**
 * The image shown when a page is shared, generated by `npm run images:build`.
 * Set explicitly rather than through Next's `opengraph-image` file convention:
 * a page's own `openGraph` object replaces the parent one wholesale, image and
 * all, so the file convention never reached a page that sets its own tags.
 */
export const SHARE_IMAGE = {
  url: `${SITE_URL}${IMAGES.share}`,
  width: 1200,
  height: 630,
  alt: "Õtekse — kolm õde pillidega mererannas",
};
