// Central registry for design image assets — the ONLY place image paths live.
//
// Files in public/images/ are generated by `npm run images:build`
// (scripts/optimize-images.mjs) from the originals in assets-src/ (gitignored;
// original photos also live in the owner's Google Drive and the Claude Design
// project). To change an image: put the original in assets-src/, rerun the
// script, and commit the optimized output.
export const IMAGES = {
  /** Hero forest photo. */
  forest: "/images/forest-enhanced.webp",
  /** Repeating wheat texture strip (alpha top edge). */
  wheat: "/images/wheat-enhanced.webp",
  /** Band photo for the About section. */
  band: "/images/band.webp",
  /** Share image for social media and chat apps, 1200x630 (lib/metadata.ts). */
  share: "/images/share.jpg",
  /** Cutout of the three sisters running (hero foreground). */
  girlsCutout: "/images/girls-cutout.webp" as string | null,
  /**
   * Poster for the Hooandja campaign video in the album section, shown until a
   * visitor presses play (AlbumVideo): a 16:9 frame of the video itself.
   */
  albumVideoPoster: "/images/album/video-poster.webp",
  /**
   * Stills of the album section that the header's "Uus album!" button opens
   * into on page load (AlbumButton), one per language. They are screenshots:
   * retake assets-src/album-preview-{et,en}.png (the scene cropped to 1307x687, header and video card hidden)
   * whenever the section changes, then rerun images:build.
   */
  albumPreview: {
    et: "/images/album/preview-et.webp",
    en: "/images/album/preview-en.webp",
  },
  /** Live photos scattered across the concerts-page hero. */
  live: {
    one: "/images/concerts/live-1.webp",
    two: "/images/concerts/live-2.webp",
    three: "/images/concerts/live-3.webp",
    four: "/images/concerts/live-4.webp",
  },
  /** Member avatars — the design's hand-positioned crops. */
  members: {
    mirtel: "/images/members/mirtel.webp",
    mirjam: "/images/members/mirjam.webp",
    katlin: "/images/members/katlin.webp",
  },
} as const;

/**
 * A timeline photo by the id timeline.json gives it: the `thumb` the grid
 * shows, and the `full` photo it opens to.
 */
export function timelinePhoto(id: string) {
  return {
    thumb: `/images/timeline/thumb/${id}.webp`,
    full: `/images/timeline/${id}.webp`,
  };
}

/**
 * The extra widths `npm run images:build` writes next to an image, by the path
 * IMAGES gives it. They live here rather than in the script because this is the
 * file the app reads; the two have to agree.
 */
const VARIANT_WIDTHS: Array<[RegExp, number[]]> = [
  [/^\/images\/band\.webp$/, [480, 800, 1000]],
  [/^\/images\/girls-cutout\.webp$/, [600, 900, 1200]],
  [/^\/images\/members\/[a-z]+\.webp$/, [240, 400, 600]],
  [/^\/images\/concerts\/live-\d\.webp$/, [450, 640, 900]],
  [/^\/images\/timeline\/thumb\/.+\.webp$/, [280, 560]],
];

/**
 * The `srcset` for one of our own images: every width that exists of it, so a
 * phone fetches a phone-sized file. Undefined for anything with no variants (a
 * product photo from the API, say), which leaves the plain `src` alone.
 *
 * Always pair it with a `sizes` describing the space the image fills — without
 * one the browser assumes the full viewport width and picks the largest file,
 * which is worse than having no srcset at all.
 */
export function srcSetFor(src: string | null | undefined): string | undefined {
  if (!src) return undefined;
  const widths = VARIANT_WIDTHS.find(([pattern]) => pattern.test(src))?.[1];
  if (!widths) return undefined;
  const max = widths[widths.length - 1];
  return widths
    .map((w) => `${w === max ? src : src.replace(/\.webp$/, `-${w}.webp`)} ${w}w`)
    .join(", ");
}

/**
 * Self-hosted video, served straight from public/videos/. The file is already
 * a web encode (H.264/AAC, 960x540, ~6 MB), so it has no build step. Replace it
 * with another web-ready 16:9 MP4; AlbumVideo shows it whole.
 */
export const VIDEOS = {
  /** The Hooandja campaign video for "Rannapiigad", in the album section. */
  hooandja: "/videos/hooandja-campaign.mp4",
} as const;
