// Central registry for design image assets — the ONLY place image paths live.
//
// Files in public/images/ are generated by `npm run images:build`
// (scripts/optimize-images.mjs) from the originals in assets-src/ (gitignored;
// original photos also live in the owner's Google Drive and the Claude Design
// project). To change an image: put the original in assets-src/, rerun the
// script, and commit the optimized output.
export const IMAGES = {
  /** Hero forest photo. */
  forest: "/images/forest-enhanced.webp",
  /** Repeating wheat texture strip (alpha top edge). */
  wheat: "/images/wheat-enhanced.webp",
  /** Band photo for the About section. */
  band: "/images/band.jpg",
  /** Cutout of the three sisters running (hero foreground). */
  girlsCutout: "/images/girls-cutout.webp" as string | null,
  /**
   * "Rannapiigad" EP cover. A stand-in for now: the band's black-and-white
   * promo square, until the real cover exists. Replace assets-src/album-cover.png
   * and update `Album.coverAlt` in messages/ to match.
   */
  albumCover: "/images/album/cover.webp",
  /**
   * Stills of the album section that the header's "Uus album!" button opens
   * into on page load (AlbumButton), one per language. They are screenshots:
   * retake assets-src/album-preview-{et,en}.png (the scene cropped to 1307x687, header hidden)
   * whenever the section changes, then rerun images:build.
   */
  albumPreview: {
    et: "/images/album/preview-et.webp",
    en: "/images/album/preview-en.webp",
  },
  /** Live photos scattered across the concerts-page hero. */
  live: {
    one: "/images/concerts/live-1.webp",
    two: "/images/concerts/live-2.webp",
    three: "/images/concerts/live-3.webp",
    four: "/images/concerts/live-4.webp",
  },
  /** Member avatars — the design's hand-positioned crops. */
  members: {
    mirtel: "/images/members/mirtel.webp",
    mirjam: "/images/members/mirjam.webp",
    katlin: "/images/members/katlin.webp",
  },
} as const;

/**
 * A timeline photo by the id timeline.json gives it: the `thumb` the grid
 * shows, and the `full` photo it opens to.
 */
export function timelinePhoto(id: string) {
  return {
    thumb: `/images/timeline/thumb/${id}.webp`,
    full: `/images/timeline/${id}.webp`,
  };
}
